apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-cicd-demo
  namespace: default


spec:
  replicas: 2

  selector:
    matchLabels:
      app: hi-cicd-demo

  template:
    metadata:
      labels:
        app: hi-cicd-demo

    spec:

      imagePullSecrets:
      - name: harbor-secret

      containers:

      - name: hi-cicd-demo

        image: docker pull harbor100.waltonbd.com:8443/demo01/hi-cicd@sha256:7e48177be447298ea5f8edd4f26c827242aad5402d8077bb606be12c862d0ade

        imagePullPolicy: Always

     
        ports:

        - containerPort: 80

