apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-cicd-demo-test222
  namespace: default


spec:
  replicas: 2

  selector:
    matchLabels:
      app: hi-cicd-demo-test222

  template:
    metadata:
      labels:
        app: hi-cicd-demo-test222

    spec:

      imagePullSecrets:
      - name: harbor-secret

      containers:

      - name: hi-cicd-demo

        image: harbor100.waltonbd.com:8443/demo01/hi-cicd

        imagePullPolicy: Always

     
        ports:

        - containerPort: 80

