apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: default

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
  - name: harbor100.waltonbd.com:8443/demo01/hi-cicd
    newName: harbor100.waltonbd.com:8443/demo01/hi-cicd
    newTag: v1
